#!/bin/bash
#
# Download raspbian and setup an emulated environmnent to test this repository
#
# Note that this will generally end up using a redis server running in the
# host environment, and not the raspbian version from the chroot.

NOOBS_URL=https://downloads.raspberrypi.org/NOOBS_latest
ROOT_TAR=os/RaspiOS_Full_armhf/root.tar.xz

set -e

# Dont install from the makefile as that leads to the emulated environment
# overwriting the qemu-arm-static binary while it is being used
sudo apt-get install -y qemu-user-static

mkdir -p tests
cd tests

# TODO
# - chase the HTTP redirections and learn the filename
# - then only download the image if we do not have that filename
#   (or, possibly if that file fails to unzip)
wget -q "$NOOBS_URL"

unzip NOOBS_latest "$ROOT_TAR"
mkdir -p raspbian
sudo tar -x -C raspbian -f "$ROOT_TAR"

sudo cp /usr/bin/qemu-arm-static raspbian/usr/bin

sudo mkdir -p raspbian/hackman
sudo chown $(whoami) raspbian/hackman
rsync -a --exclude=tests ../ raspbian/hackman/

sudo chroot raspbian apt-get update
sudo chroot raspbian apt-get install -y make sudo
sudo chroot raspbian make -C hackman build-depends
sudo chroot raspbian make -C hackman test.unit
