# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hackman_payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
    ]
