# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackman_payments", "0004_auto_20170217_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttag",
            name="hashtag",
            field=models.CharField(db_index=True, default="dues", max_length=10),
        ),
        migrations.AlterField(
            model_name="paymenttag",
            name="tag",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
