# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackman_payments', '0006_auto_20170308_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttag',
            name='hashtag',
            field=models.CharField(db_index=True, default='dues', max_length=20),
        ),
    ]
