# Generated by Django 2.0.1 on 2018-01-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackman_payments', '0007_auto_20170308_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttag',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
