# Generated by Django 4.0.4 on 2022-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackman_payments", "0008_auto_20180109_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttag",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
